# Generated by Django 5.0.6 on 2024-07-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0002_remove_survey_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question1", models.IntegerField(default=0)),
                ("question2", models.IntegerField(default=0)),
                ("question3", models.IntegerField(default=0)),
            ],
        ),
    ]
