# Generated by Django 5.0.6 on 2024-07-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0003_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="data",
            old_name="question1",
            new_name="age",
        ),
        migrations.RenameField(
            model_name="data",
            old_name="question2",
            new_name="blood_pressure",
        ),
        migrations.RenameField(
            model_name="data",
            old_name="question3",
            new_name="bmi",
        ),
        migrations.AddField(
            model_name="data",
            name="diabetes_pedigree_function",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="data",
            name="glucose",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="data",
            name="insulin",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="data",
            name="outcome",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="data",
            name="pregnancies",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="data",
            name="skin_thickness",
            field=models.IntegerField(default=0),
        ),
    ]
